import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { auth } from '../lib/firebase';
import { 
  FileText, 
  ShieldCheck, 
  Dices, 
  Target, 
  ChevronRight,
  Download,
  Eye,
  BrainCircuit,
  Lightbulb
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '../lib/utils';

type Mode = "safe" | "balanced" | "surprise";

export default function PredictionPapers() {
  const { user, showNotification } = useApp();
  const [subject, setSubject] = useState<'SFT' | 'ET' | 'ICT'>('SFT');
  const [mode, setMode] = useState<Mode>("balanced");
  const [loading, setLoading] = useState(false);
  const [paper, setPaper] = useState<any>(null);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const token = user?.token || await auth.currentUser?.getIdToken();
      const res = await fetch('/api/exam-intel/predicted-paper', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}` 
        },
        body: JSON.stringify({
          subject,
          mode,
          targetMarks: 80,
          includeAnswers: true
        })
      });
      const data = await res.json();
      setPaper(data);
      showNotification("Predicted Revision Paper Generated!", "success");
    } catch (err) {
      showNotification("Failed to generate paper", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12">
      <header>
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight flex items-center gap-2">
          <BrainCircuit className="w-8 h-8 text-indigo-600" />
          Prediction Papers
        </h1>
        <p className="text-gray-500 mt-1">Simulated revision papers generated by AI pattern analysis</p>
      </header>

      {!paper ? (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="md:col-span-1 space-y-6">
            <div className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm space-y-6">
              <div>
                <label className="text-xs font-bold text-gray-400 uppercase tracking-widest block mb-3">Target Subject</label>
                <div className="flex bg-gray-50 p-1 rounded-xl">
                  {['SFT', 'ET', 'ICT'].map(sub => (
                    <button
                      key={sub}
                      onClick={() => setSubject(sub as any)}
                      className={cn(
                        "flex-1 py-2 rounded-lg text-sm font-bold transition-all",
                        subject === sub ? "bg-white text-indigo-600 shadow-sm" : "text-gray-500 hover:text-gray-700"
                      )}
                    >
                      {sub}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="text-xs font-bold text-gray-400 uppercase tracking-widest block mb-3">Simulation Mode</label>
                <div className="space-y-2">
                  {[
                    { id: 'safe', title: 'Safe / Foundation', desc: 'Focus on 100% recurring high-yield topics.', icon: ShieldCheck },
                    { id: 'balanced', title: 'Balanced / Standard', desc: 'Mix of high-yield and rotation topics.', icon: Target },
                    { id: 'surprise', title: 'Hard / Surprise', desc: 'Focus on rarely asked syllabus concepts.', icon: Dices },
                  ].map(m => (
                    <button
                      key={m.id}
                      onClick={() => setMode(m.id as Mode)}
                      className={cn(
                        "w-full p-4 rounded-xl border text-left transition-all",
                        mode === m.id ? "border-indigo-600 bg-indigo-50/50" : "border-gray-100 hover:border-indigo-200"
                      )}
                    >
                      <div className="flex items-center gap-3 mb-1">
                        <m.icon className={cn("w-4 h-4", mode === m.id ? "text-indigo-600" : "text-gray-400")} />
                        <span className={cn("font-bold text-sm", mode === m.id ? "text-indigo-900" : "text-gray-700")}>{m.title}</span>
                      </div>
                      <p className="text-xs text-gray-500">{m.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              <button
                onClick={handleGenerate}
                disabled={loading}
                className="w-full py-4 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-600/20 disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {loading ? "Simulating Exam..." : "Generate Predicted Paper"}
                <ChevronRight className="w-5 h-5" />
              </button>
            </div>
          </div>

          <div className="md:col-span-2 space-y-6">
            <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-8 space-y-4">
              <div className="w-12 h-12 bg-white rounded-xl flex items-center justify-center shadow-sm">
                <Lightbulb className="w-6 h-6 text-indigo-600" />
              </div>
              <h3 className="text-xl font-bold text-indigo-900">How these papers are built</h3>
              <p className="text-indigo-700 text-sm leading-relaxed">
                Review past-paper patterns, current syllabus weights, and topic coverage in one place.
                It cross-references this with what hasn't appeared recently to build a revision paper that targets high-probability areas.
              </p>
              <ul className="space-y-2 pt-2">
                {[
                  "Uses evidence from 2009-2024 papers",
                  "Prioritizes syllabus-weight heavy lessons",
                  "Includes MCQ, Structured, and Essay models",
                  "Generates marking schemes for self-correction"
                ].map((text, i) => (
                  <li key={i} className="flex items-center gap-2 text-xs text-indigo-600 font-medium">
                    <div className="w-1 h-1 bg-indigo-400 rounded-full" />
                    {text}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <button 
              onClick={() => setPaper(null)}
              className="text-sm font-bold text-gray-500 hover:text-gray-700 flex items-center gap-1"
            >
              <ChevronRight className="w-4 h-4 rotate-180" /> Back to Settings
            </button>
            <div className="flex gap-2">
              <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg"><Eye className="w-5 h-5" /></button>
              <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg"><Download className="w-5 h-5" /></button>
            </div>
          </div>

          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-12 max-w-4xl mx-auto space-y-8">
            <div className="text-center space-y-2 border-b border-gray-100 pb-8">
              <h2 className="text-2xl font-bold text-gray-900 uppercase">Predicted Revision Paper - {subject}</h2>
              <p className="text-sm text-indigo-600 font-bold uppercase tracking-widest">{mode} Simulation Mode</p>
              <p className="text-xs text-gray-400">Generated for Revision Purposes Only • Clora X Exam Intelligence</p>
            </div>

            <div className="space-y-12">
              {paper.questions.map((q: any) => (
                <div key={q.questionNo} className="space-y-4">
                  <div className="flex items-start gap-4">
                    <span className="font-bold text-lg text-gray-900">{q.questionNo}.</span>
                    <div className="space-y-4 flex-1">
                      <p className="text-gray-800 font-medium leading-relaxed">{q.text}</p>
                      
                      {q.options && q.options.length > 0 && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pl-4">
                          {q.options.map((opt: string, idx: number) => (
                            <div key={idx} className="flex items-center gap-2 text-sm text-gray-600">
                              <div className="w-6 h-6 border border-gray-200 rounded flex items-center justify-center text-[10px] font-bold">
                                {String.fromCharCode(65 + idx)}
                              </div>
                              {opt}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {paper.answerKey && (
              <div className="pt-12 border-t border-gray-100 mt-12">
                <h3 className="font-bold text-gray-900 mb-6 flex items-center gap-2">
                  <ShieldCheck className="w-5 h-5 text-emerald-600" />
                  AI Marking Scheme & Evidence
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-4">
                    <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Answer Key</h4>
                    <div className="grid grid-cols-5 gap-2">
                      {paper.answerKey.map((ans: string, i: number) => (
                        <div key={i} className="bg-gray-50 p-2 rounded text-center text-xs font-bold text-gray-700">
                          {i + 1}. {ans}
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="space-y-4">
                    <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Intelligence Evidence</h4>
                    <div className="space-y-2">
                      {paper.evidenceMap.slice(0, 5).map((ev: any) => (
                        <div key={ev.questionNo} className="text-[10px] text-gray-500 bg-gray-50 p-2 rounded">
                          <span className="font-bold">Q{ev.questionNo}:</span> {ev.evidence}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
