// Vercel transpiles TypeScript without rewriting extensionless imports in the
// backend dependency graph. Import the esbuild-generated ESM bundle instead so
// the function always boots from one fully-resolved JavaScript module.
// @ts-ignore Generated by npm run build:vercel before Vercel bundles api/index.ts.
import app from '../vercel-runtime/server.mjs';
export default app;
